### ISSUE TITLE
Buttons in nav?

### ISSUE THREAD

**Issue by BANOnotIT** [Borderliner/Meshki#10]
Why do you use `<button onclick="location.href='something'">` against `<a href="something">`? I know, that you use `.sidenav button` selector, but why do you use it?

**Comment by BANOnotIT** [comment]
Why not to use `.sidenav .button`?

**Comment by Borderliner** [comment]
@BANOnotIT You can use either of them, it doesn't really matter. I've used buttons to show that it's possible to put buttons inside Sidenav too.

Thanks for the report! 👍
