### ISSUE TITLE
Meshki in Editor (atom , vim , MS VsCode , ...)

### ISSUE THREAD

**Issue by Pakrohk** [Borderliner/Meshki#12]
سعی کنید پلا گینی برای پشتیباینی اتوکامپلیت برای ادیتور ها آماده کنید
معمولا کتاب خونه های دیگه این عمکانات رو دارند

Translation: Please try to implement an autocomplete plugin to support various editors. Other libraries usually tend to provide such plugins.

**Comment by Borderliner** [comment]
ازتون بابت این گزارش ممنونم.
سعی کردم مشکی رو طوری طراحی کنم که برنامه‌نویس نیاز نداشته باشه به حفظ کردن اسامی و عبارات عجیب و غریب، و سعی کردم همه چیز رو ساده نگه دارم. داشتن یه پلاگین چیز خوبی به نظر میاد، ولی به نظرم ضروری نیست. هرچند وجود چنین چیزی جالبه، اما متاسفانه به تنهایی از پس نگه داری پکیج‌های پلاگین برنمیام. بازم ممنونم دوست عزیز.

Translation: Thanks for the report.
I've tried to design Meshki in a way that a developer wouldn't need to memorize weird names and expressions for library structures, and I've tried to keep it as simple as possible. Having an autocomplete plugin seems nice, but it's not necessary. Though it's interesting to have such a thing, I can't afford maintaining different plugin packages. Thank you again, dear friend.
