### ISSUE TITLE
Wrong padding css?

### ISSUE THREAD

**Issue by kamyker** [Borderliner/Meshki#19]
Seems like "auto" is wrong value for padding

![padding5](https://user-images.githubusercontent.com/9093037/67167271-0a021d00-f398-11e9-895d-2c5e7009953a.png)

**Comment by Borderliner** [comment]
Thanks. I'll look into this on the weekend. Meanwhile, if you can fix and test this, I'll merge your pull request. Until then, I'll keep this issue open.

**Comment by Borderliner** [comment]
Bug fixed in [v2.5.0](https://github.com/Borderliner/Meshki/releases/tag/v2.5.0)
