### ISSUE TITLE
Footer is not at the bottom with not enough content

### ISSUE THREAD

**Issue by kamyker** [Borderliner/Meshki#20]
To see this issue go to https://borderliner.github.io/Meshki/, delete most of the divs in the content:
![footer](https://user-images.githubusercontent.com/9093037/67167698-44ba8400-f39d-11e9-870f-6fc69b3ca3b9.png)

**Comment by Borderliner** [comment]
This is not a bug. The same thing happens with twitter bootstrap. If you don't have enough content to fill your page, this happens. You can easily fix this in your custom css like this:

```
position: fixed;
width: 100%;
bottom: 0;
```
