### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by ivanhuay** [Borderliner/Meshki#3]
I can not enter the sample site

http://meshki.borderliner.ir/

**Comment by Borderliner** [comment]
It's hosted on a weak shared hosting, but mine works fine now. Try again after a while and try refreshing your browser with Ctrl+F5. Let me know if you experience it again.

**Comment by ivanhuay** [comment]
Did you test the github pages?

https://pages.github.com/

**Comment by Borderliner** [comment]
I'm gonna host it on GitHub soon. Thanks for the report.

**Comment by Borderliner** [comment]
Meshki is now hosted on GitHub Pages. Thank you for your feedback.
https://borderliner.github.io/Meshki/
