### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by xeruf** [Borderliner/Meshki#30]
Hey, I looked at Meshki a while ago and it looked quite interesting, but now development seems to have stalled.
Are you still using it or would you suggest using something else today?

**Comment by Borderliner** [comment]
@xeruf Hello. Meshki's development is currently stalled, but that doesn't mean it's dead. I just find myself too lonely to work on this and need some sort of incentive to go on. I've been thinking of porting it to a major frontend framework like Vue.js but the code needs a little clean up.
And hey, any kind of contribution is more than welcome. The code is easy to get into and it's a great experience for css devs.

**Comment by xeruf** [comment]
not a css dev, just looking for a safe choice for frontend development ;) thanks for your efforts already, either way!
so, are you using it yourself or do you know any example projects? In that case a little gallery in the readme might be good.

**Comment by Borderliner** [comment]
@xeruf  I don't think it's a "safe" choice for front-end development.

**Comment by Borderliner** [comment]
The project is currently being maintained and growing. So I'm closing this issue.
