### ISSUE TITLE
2017 and no flexbox?

### ISSUE THREAD

**Issue by v3ss0n** [Borderliner/Meshki#4]

**Comment by Borderliner** [comment]
I'm not really sure about a big change to the layout system. Any reasons you might have?

**Comment by danielpetrica** [comment]
It would be useful on tables to make it more readable on phones. 
For example, http://thememaker.site/app/expert_start.php, when used on a phone, is not too nice. 
With flexbox, we could downscale faster the colors column, and adding some other minor fixes.

**Comment by Borderliner** [comment]
@danielpetrica I'm currently working on re-writing Meshki with Less. If I have the time, I may be able to add a secondary layout system (but again, Meshki will be distributed using its default grid layout). You are more than welcome to contribute to our "less-dev" branch. Fork the project, check out "less-dev", and make a pull request.

**Comment by Borderliner** [comment]
Feature added in [v2.5.0](https://github.com/Borderliner/Meshki/releases/tag/v2.5.0)
