### ISSUE TITLE
navbar covering the container

### ISSUE THREAD

**Issue by danielpetrica** [Borderliner/Meshki#5]
New Issue
![thememaker site generator page telegram theme maker](https://cloud.githubusercontent.com/assets/4850686/22251933/cd0aae30-e24c-11e6-9af8-9f56e751c65e.png)

As you can see the nav bar is covering the container, to prevent this I added a padding at the top of the title, but is there another way to correct it? I think that different div shouldn't overlap

Old issue:  
The issue exist on http://thememaker.site/generator if you go to the table you can see a strange line cutting the first row. (i'm on windows 10 x64, with google chrome)
That's a screenshoot: 
![thememaker site generator page telegram theme maker](https://cloud.githubusercontent.com/assets/4850686/22239857/9af6112a-e218-11e6-829c-f955c59d01c1.png)

**Comment by Borderliner** [comment]
I couldn't see anything. But thank you for your bug report.

**Comment by Borderliner** [comment]
You seem to have made a mistake regarding the layout though. The proper layout is:

```
body
    sidenav
    content
        nav
        container
        footer
```

**Comment by danielpetrica** [comment]
hi, yes I saw that the error was on my side, that's why I closed it. thanks.

**Comment by danielpetrica** [comment]
@Borderliner  I had some issue with the navbar covering the container, when I cancel the title padding (added by me)

**Comment by Borderliner** [comment]
This is going to be fixed in the next release. For now, all you have to do is to set a margin-top of 60px for your container.

```
.container {
  margin-top: 60px;
}
```
I'll keep this open until the next point release.

**Comment by Borderliner** [comment]
Docs were updated to contain the latest structure to build Meshki.
