### ISSUE TITLE
Error 404 for "[Plugin] Extra Button Colors" link

### ISSUE THREAD

**Issue by danielpetrica** [Borderliner/Meshki#6]
#Error 404
I tried to open the link contained in the link tag bellow and is giving a 404 error. 
The link is: https://cdnjs.cloudflare.com/ajax/libs/meshki/1.5.1/button-colors.min.css
The code on the  https://borderliner.github.io/Meshki/ page it's in the "[Plugin] Extra Button Colors" section
`<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/meshki/1.5.1/button-colors.min.css">          `

**Comment by Borderliner** [comment]
Thank you for reporting the issue. The actual link is:
[https://cdnjs.cloudflare.com/ajax/libs/meshki/1.5.1/plugins/button-colors.min.css](https://cdnjs.cloudflare.com/ajax/libs/meshki/1.5.1/plugins/button-colors.min.css)
I'll update the docs now.
