### ISSUE TITLE
Some suggestions to make Meshki a general-purpose library

### ISSUE THREAD

**Issue by Pakrohk** [Borderliner/Meshki#7]
اول برای قرار دادن عکس و مدیریت اون در مشکی زیاد توضیحی داده نشده وجود این امکان بسیار لازم است 
.امکان اپلود فایل را راحت تر کنید به شکلی که حجم, اندازه,نوع(فرمت فایل) و برش(برای عکس ها) مدیریت شود
و همین طور 
ui 
زیبای برای ستون های درصدی و مدیریت اپلود قرار بگیرد
دوم یک باگ در کپی شدن متن های کد وجود دارد مشکی باید به نوعی باشد که اگر باکسی برای کد تایین شد 
.متن اون جدا گونه از متن صفحه باشد و در کلید برد کپی شود

**Comment by Borderliner** [comment]
خیلی ممنونم بابت پیشنهادات و گزارش باگ.
در مورد قرار دادن عکس در نسخه بعد حتما توضیحات بیشتری ارائه خواهد شد.
درباره مدیریت فایل و ویرایش عکس باید بگم که تلاش ما برای ساخت یک کتابخونه به شدت مجهز نیس. نه نیروی کارش رو داریم، نه هدفمون از اول همین بوده. ولی مشکی اجزای ساده تری رو معرفی میکنه تا با استفاده از اونا بشه اجزای پیچیده تری ساخت.
مشکل کپی کد به خاطر وجود فاصله در کد اچ‌تی‌ام‌ال هست، و اگه زیباساز کد داشته باشید، میتونید مشکل رو سریع رفع کنید. اما تلاش من بر این هست تا در نسخه بعدی، مشکل کپی کد رو حل کنم.

برنامه ما برای نسخه بعدی (یعنی نسخه ۲)، بازنویسی مشکی به وسیله اس‌سی‌اس‌اس هست. اگه تجربه کافی دارید، میتونید به شاخه:
sass-dev
کمک کنید! متشکرم ازتون.

**Comment by Borderliner** [comment]
Code snippet copying problem was addressed in v2.0.0. Closing this issue.
