### ISSUE TITLE
How to add the Persian plugin?

### ISSUE THREAD

**Issue by ALi23rh54** [Borderliner/Meshki#8]
سلام چطور پلاگین فارسیه مشکی رو اضافه کنم اون قسمت سایت باز نمیشه

**Comment by Borderliner** [comment]
به اینجا سر بزنید: https://borderliner.github.io/Meshki/rtl/
دکمه قرمز رنگ «استفاده از سی‌دی‌ان» رو بزنید، و سومین خط رو به عنوان کد سی‌اس‌اس به صفحه وبتون اضافه کنید.

**Comment by ALi23rh54** [comment]
بخش کشو به درستی کار نمی کند آیا در مشکی 1.5.1 
تغییر کرده است ؟

**Comment by Borderliner** [comment]
بله، از ورژن ۱.۵.۰ تغییراتی ایجاد شده که باعث بهم ریختن کدهای ورژن قبلی میشه. اطلاعیه‌ش توی سایت زده شده. احتمالا اگه جای تگ‌های:
container
و 
content
رو باهم عوض کنید، مشکل حل میشه.
