### ISSUE TITLE
bug  = nav and div class nav

### ISSUE THREAD

**Issue by Pakrohk** [Borderliner/Meshki#9]
سلام این یک مشکل در منو هستش که باید حل بشه 
برای ساخت منو باید از تک های 
nav , nav fixed , div (class ="nav") , div (class ="nav fixed ")
استفاده کرد ولی این باعث میشه که در پارا گراف نویسی مشکل ایجاد بشه و روی دایو 
پارا گراف قرار می گیره و اولین جمله پراگراف یا حرف در صورت وجود 
fixed 
زیر منو 
و در صورت نبود اون 
روی منو 
قرار می گیرد و در کار کرد اون مشکل ایجاد می کند
![screenshot 25](https://cloud.githubusercontent.com/assets/27810360/26351067/b58f56cc-3f6a-11e7-98bb-a81c188bfdea.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/27810360/26351124/ff6e3b82-3f6a-11e7-945a-c8f8055e8323.png)

**Comment by Borderliner** [comment]
ممنون از کزارش باگ.
ولی این یک باگ نیست، و عمدا اینطور طراحی شده تا برنامه نویس بتونه خودش ارتفاع از بالای صفحه رو تنظیم کنه، با استفاده از:
margin-top: 60px;
برروی
container
بالایی. درضمن، احتمالا مطلع هستید که لازم نیست از تمامی تگ هایی که معرفی کردید استفاده کنید. اگر احساس میکنید چنین طراحی ای مناسب نیست، حتما بگید، یا اگر در توانتون هست، پروژه رو فورک کنید و 
 Pull Request
بدید. بسیار ممنونم.

**Comment by Pakrohk** [comment]
بعله در جریانم و پرسیدم تا دیگران هم مثل من به مشکل بر نخورن ولی خودم باکمی کار درستش کردم 
باید کلاس 
(content)
رو درست می کردی
درضمن سرج در مشکی کمی سخت هستش کد ها کمی بهم ریخته سیو شدن مجوبر میشی در کلاسی جدید معرفی کنی معمولا به همون نام
و سرج در وب به وسیله مشکی هم کمی کند(منظور از کند نیاز به کار بیشتر  هست) که خودم یه اسکریبت جاوا براش درست کردم که بعدا قرارش میدم که به صورت پلاگین اضافش کنید.

**Comment by Borderliner** [comment]
معذرت میخوام، ولی متوجه نشدم منظورتون از سرچ در مشکی چیه. اگه منظورتون جستجوی مطالب درون راهنمای مشکیه، لطفا یه
Issue
دیگه ای باز کنید و مشکل رو اونجا توضیح بدید. من این مشکل رو میبندم.
